// SPDX-License-Identifier: GPL-3.0-or-later
package scaffold

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/voxpupuli/jig/internal/config"
	"github.com/voxpupuli/jig/internal/module"
)

func NewModule(opts Options) error {
	if err := validateComponentName(opts.Name); err != nil {
		return fmt.Errorf("invalid module name: %w", err)
	}

	baseDir := opts.TargetDir
	if baseDir == "" {
		cwd, err := os.Getwd()
		if err != nil {
			return fmt.Errorf("failed to get working directory: %w", err)
		}
		baseDir = cwd
	}

	moduleDir := filepath.Join(baseDir, opts.Name)

	renderer := newRenderer(opts.TemplateDir)

	// The module scaffold is the template tree itself: every file under
	// module/ is written to the same relative path in the new module, so
	// custom template dirs can add files without any code mapping (#36).
	// metadata.json and jig.toml are generated by jig and stay reserved.
	// Listed before anything is written so a broken tree fails cleanly.
	entries, err := renderer.ListTree("module")
	if err != nil {
		return fmt.Errorf("failed to list module templates: %w", err)
	}

	var templates []TemplateFile
	for _, entry := range entries {
		if entry == "metadata.json" || entry == "jig.toml" {
			fmt.Fprintf(os.Stderr, "warning: ignoring %s in template tree: it is generated by jig\n", entry)
			continue
		}
		templates = append(templates, TemplateFile{
			FileName:    "module/" + entry,
			Destination: filepath.Join(moduleDir, filepath.FromSlash(entry)),
		})
	}

	if _, err := os.Stat(moduleDir); err == nil {
		if !opts.Force {
			return fmt.Errorf("directory %s already exists, use --force to replace it", moduleDir)
		}
		if err := BackupDir(moduleDir); err != nil {
			return fmt.Errorf("failed to back up existing directory: %w", err)
		}
		fmt.Printf("Renamed existing directory %s\n", moduleDir)
	}

	if err := os.MkdirAll(moduleDir, 0755); err != nil {
		return fmt.Errorf("failed to create directory %s: %w", moduleDir, err)
	}

	meta := module.NewMetadata(opts.Name, opts.ForgeUser, opts.Author)
	meta.License = opts.License
	meta.Summary = opts.Summary
	meta.Source = opts.Source

	if err := meta.Write(filepath.Join(moduleDir, "metadata.json")); err != nil {
		return fmt.Errorf("failed to write metadata.json: %w", err)
	}

	moduleConfig := config.ModuleConfig{
		Template: config.ModuleTemplate{
			URL:    opts.TemplateURL,
			Ref:    opts.TemplateRef,
			Commit: opts.TemplateCommit,
		},
	}
	if err := moduleConfig.Write(moduleDir); err != nil {
		return err
	}

	data := struct {
		ModuleName string
		ForgeUser  string
		Author     string
		License    string
		ClassName  string
	}{
		ModuleName: opts.Name,
		ForgeUser:  opts.ForgeUser,
		Author:     opts.Author,
		License:    opts.License,
		ClassName:  opts.Name,
	}

	if err := RenderTemplates(renderer, templates, data, opts.Force); err != nil {
		return fmt.Errorf("failed to render templates: %w", err)
	}

	fmt.Printf("Created new module %s in %s\n", opts.Name, moduleDir)
	return nil
}
