// SPDX-License-Identifier: GPL-3.0-or-later
package scaffold

import (
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"

	gogitignore "github.com/go-git/go-git/v5/plumbing/format/gitignore"
	"github.com/sergi/go-diff/diffmatchpatch"
	"github.com/voxpupuli/jig/internal/config"
)

// RenewOptions controls Renew. Paths is the [renew] allowlist from jig.toml:
// gitignore-style globs matched against output paths relative to the module
// root, naming the files renew may re-render and overwrite.
type RenewOptions struct {
	ModuleDir   string
	TemplateDir string
	Paths       []string
	DryRun      bool
	Out         io.Writer
}

// Renew re-renders the module template tree over an existing module. Only
// files matching the allowlist are touched: changed files are overwritten
// (or, with DryRun, reported with a diff), files whose rendered content
// already matches are left alone, and allowlisted files missing from the
// module are created.
func Renew(opts RenewOptions) error {
	out := opts.Out
	if out == nil {
		out = os.Stdout
	}

	meta, err := GetMetadata(opts.ModuleDir)
	if err != nil {
		return err
	}

	renderer := newRenderer(opts.TemplateDir)
	entries, err := renderer.ListTree("module")
	if err != nil {
		return fmt.Errorf("failed to list module templates: %w", err)
	}

	var patterns []gogitignore.Pattern
	for _, p := range opts.Paths {
		patterns = append(patterns, gogitignore.ParsePattern(p, nil))
	}
	matcher := gogitignore.NewMatcher(patterns)

	data := moduleTemplateData{
		ModuleName: meta.ModuleName(),
		ForgeUser:  meta.ForgeUsername(),
		Author:     meta.Author,
		License:    meta.License,
		ClassName:  meta.ModuleName(),
	}

	renewed, upToDate := 0, 0
	for _, entry := range entries {
		if !matcher.Match(strings.Split(entry, "/"), false) {
			continue
		}
		if entry == "metadata.json" || entry == config.ModuleConfigFileName {
			fmt.Fprintf(os.Stderr, "warning: %s is generated by jig and cannot be renewed\n", entry)
			continue
		}

		rendered, err := renderer.Render("module/"+entry, data)
		if err != nil {
			return fmt.Errorf("failed to render template %s: %w", entry, err)
		}

		dest := filepath.Join(opts.ModuleDir, filepath.FromSlash(entry))
		current, readErr := os.ReadFile(dest)
		if readErr != nil && !os.IsNotExist(readErr) {
			return fmt.Errorf("failed to read %s: %w", dest, readErr)
		}
		if readErr == nil && string(current) == rendered {
			upToDate++
			continue
		}

		if opts.DryRun {
			fmt.Fprintf(out, "would renew %s:\n", entry)
			fmt.Fprint(out, lineDiff(string(current), rendered))
		} else {
			if err := os.MkdirAll(filepath.Dir(dest), 0755); err != nil {
				return fmt.Errorf("failed to create directory %s: %w", filepath.Dir(dest), err)
			}
			if err := os.WriteFile(dest, []byte(rendered), 0644); err != nil {
				return fmt.Errorf("failed to write %s: %w", dest, err)
			}
			fmt.Fprintf(out, "renewed %s\n", entry)
		}
		renewed++
	}

	switch {
	case renewed == 0 && upToDate == 0:
		fmt.Fprintln(out, "no template files match the [renew] paths allowlist in "+config.ModuleConfigFileName)
	case opts.DryRun:
		fmt.Fprintf(out, "%d file(s) would be renewed, %d already up to date\n", renewed, upToDate)
	default:
		fmt.Fprintf(out, "%d file(s) renewed, %d already up to date\n", renewed, upToDate)
	}
	return nil
}

// lineDiff returns a minimal line-based diff between old and new content:
// removed lines prefixed with "-", added lines with "+", unchanged lines
// omitted. Both sides are indented so diff lines stand apart from jig's own
// output.
func lineDiff(oldText, newText string) string {
	dmp := diffmatchpatch.New()
	oldChars, newChars, lines := dmp.DiffLinesToChars(oldText, newText)
	diffs := dmp.DiffCharsToLines(dmp.DiffMain(oldChars, newChars, false), lines)

	var sb strings.Builder
	for _, d := range diffs {
		var prefix string
		switch d.Type {
		case diffmatchpatch.DiffDelete:
			prefix = "-"
		case diffmatchpatch.DiffInsert:
			prefix = "+"
		default:
			continue
		}
		for line := range strings.Lines(d.Text) {
			sb.WriteString("  ")
			sb.WriteString(prefix)
			sb.WriteString(strings.TrimSuffix(line, "\n"))
			sb.WriteString("\n")
		}
	}
	return sb.String()
}
